### ISSUE TITLE
不知道能不能解决

### ISSUE THREAD

**Issue by n2XdReamer** [2601677867/One-Click-Run_Source_Server#2]
Git 安装时报错
Log:
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following additional packages will be installed:
  git-man liberror-perl patch
Suggested packages:
  git-daemon-run | git-daemon-sysvinit git-doc git-el git-email git-gui gitk gitweb git-cvs git-mediawiki git-svn ed
  diffutils-doc
The following NEW packages will be installed:
  git git-man liberror-perl patch
0 upgraded, 4 newly installed, 0 to remove and 0 not upgraded.
Need to get 7,397 kB of archives.
After this operation, 38.2 MB of additional disk space will be used.
Do you want to continue? [Y/n] Y
Get:1 http://mirrors.aliyun.com/debian buster/main amd64 liberror-perl all 0.17027-2 [30.9 kB]
Err:2 http://mirrors.aliyun.com/debian buster/main amd64 git-man all 1:2.20.1-2+deb10u1
  404  Not Found [IP: 116.0.89.209 80]
Err:3 http://mirrors.aliyun.com/debian buster/main amd64 git amd64 1:2.20.1-2+deb10u1
  404  Not Found [IP: 116.0.89.209 80]
Get:4 http://mirrors.aliyun.com/debian buster/main amd64 patch amd64 2.7.6-3+deb10u1 [126 kB]
Fetched 157 kB in 3s (45.7 kB/s)
E: Failed to fetch http://mirrors.aliyun.com/debian/pool/main/g/git/git-man_2.20.1-2+deb10u1_all.deb  404  Not Found [IP: 116.0.89.209 80]
E: Failed to fetch http://mirrors.aliyun.com/debian/pool/main/g/git/git_2.20.1-2+deb10u1_amd64.deb  404  Not Found [IP: 116.0.89.209 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
root@RainYunKNGPmKn8:~# git clone https://github.com/2601677867/One-Click-Run_Source_Server.git
-bash: git: command not found
root@RainYunKNGPmKn8:~# git
-bash: git: command not found
root@RainYunKNGPmKn8:~# apt install git
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following additional packages will be installed:
  git-man liberror-perl patch
Suggested packages:
  git-daemon-run | git-daemon-sysvinit git-doc git-el git-email git-gui gitk gitweb git-cvs git-mediawiki git-svn ed
  diffutils-doc
The following NEW packages will be installed:
  git git-man liberror-perl patch
0 upgraded, 4 newly installed, 0 to remove and 0 not upgraded.
Need to get 7,239 kB/7,397 kB of archives.
After this operation, 38.2 MB of additional disk space will be used.
Do you want to continue? [Y/n] Y
Err:1 http://mirrors.aliyun.com/debian buster/main amd64 git-man all 1:2.20.1-2+deb10u1
  404  Not Found [IP: 116.0.89.206 80]
Err:2 http://mirrors.aliyun.com/debian buster/main amd64 git amd64 1:2.20.1-2+deb10u1
  404  Not Found [IP: 116.0.89.206 80]
E: Failed to fetch http://mirrors.aliyun.com/debian/pool/main/g/git/git-man_2.20.1-2+deb10u1_all.deb  404  Not Found [IP: 116.0.89.206 80]
E: Failed to fetch http://mirrors.aliyun.com/debian/pool/main/g/git/git_2.20.1-2+deb10u1_amd64.deb  404  Not Found [IP: 116.0.89.206 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
怎么办。。下载不了脚本

**Comment by 2601677867** [comment]
看起来像是您服务器自身apt-get 或 yum  install命令无法运行。更换下系统源试试
