### ISSUE TITLE
英灵神殿 892970 No subscription

### ISSUE THREAD

**Issue by tamageci86** [2601677867/One-Click-Run_Source_Server#3]
Connecting anonymously to Steam Public...Logged in OK
Waiting for user info...OK
ERROR! Failed to install app '892970' (No subscription)

**Comment by 2601677867** [comment]
在steam数据库中没有steamid为892970的服务端文件，请访问https://developer.valvesoftware.com/wiki/Steam_Application_IDs
或steamdb来查询正确Appid
